# SPDX-PackageSummary: 2ping - A bi-directional ping utility
# SPDX-FileCopyrightText: Copyright (C) 2010-2025 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0
---
fail_fast: false

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.4.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-case-conflict"
      - id: "check-executables-have-shebangs"
      - id: "check-xml"
      - id: "check-yaml"
        args:
          - "--unsafe"
      - id: "check-json"
      - id: "check-shebang-scripts-are-executable"
      - id: "detect-private-key"
      - id: "end-of-file-fixer"
      - id: "fix-byte-order-marker"
      - id: "requirements-txt-fixer"
      - id: "trailing-whitespace"

  - repo: "https://github.com/adrienverge/yamllint.git"
    rev: "v1.32.0"
    hooks:
      - id: "yamllint"
        args:
          - "-c"
          - ".yamllint.yml"

  - repo: "https://github.com/psf/black"
    rev: "25.1.0"
    hooks:
      - id: "black"

  - repo: "https://github.com/pycqa/flake8"
    rev: "7.2.0"
    hooks:
      - id: "flake8"
        additional_dependencies: ["Flake8-pyproject"]

  - repo: "https://github.com/rhysd/actionlint"
    rev: "v1.7.7"
    hooks:
      - id: "actionlint"

  - repo: "https://github.com/fsfe/reuse-tool"
    rev: "v5.0.2"
    hooks:
      - id: "reuse"
