language: python
jobs:
  include:
    - name: "Python 3.5"
      python: "3.5"
      env:
        - TOX_SKIP_ENV=black
    - name: "Python 3.6"
      python: "3.6"
    - name: "Python 3.7"
      python: "3.7"
    - name: "Python 3.8"
      python: "3.8"
install:
  - python -mpip install tox
script:
  - python -mtox
