language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install distro
  - pip install dnspython
  - pip install netifaces
  - pip install pycrypto
  - python -c 'import sys; sys.exit(0 if sys.version_info[0:2] == (3, 5) else 1)' || pip install black
  - pip install flake8
  - pip install .
script:
  - make lint
  - python -c 'import sys; sys.exit(0 if sys.version_info[0:2] == (3, 5) else 1)' || black --check
  - python setup.py test
  - python setup.py check
  - python setup.py sdist
