#!/usr/bin/env python3

# 2ping - A bi-directional ping utility
# Copyright (C) 2010-2021 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

import sys
import twoping.cli


def module_init():
    if __name__ == "__main__":
        sys.exit(twoping.cli.main(sys.argv))


module_init()
