#!/usr/bin/env python3

# SPDX-PackageSummary: 2ping - A bi-directional ping utility
# SPDX-FileCopyrightText: Copyright (C) 2010-2025 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

from pathlib import Path
from runpy import run_module
import sys


sys.path.insert(0, str(Path(__file__).resolve().parent))
run_module("twoping.cli", run_name="__main__")
