#!/usr/bin/env python3

# SPDX-PackageName: 2ping
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/2ping
# SPDX-FileCopyrightText: © 2010 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

from pathlib import Path
from runpy import run_module
import sys


sys.path.insert(0, str(Path(__file__).resolve().parent))
run_module("twoping.cli", run_name="__main__")
