name: snapcraft
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        use_lxd: true
    - name: Build snap
      run: |
        sudo usermod --append --groups lxd $USER
        sg lxd -c 'snapcraft --use-lxd'
    - name: Upload snap
      uses: actions/upload-artifact@v2
      with:
        name: 2ping-snap-${{ github.job }}-${{ github.run_id }}.${{ github.run_number }}-${{ runner.os }}
        path: "*.snap"
